### ISSUE TITLE
Scrolling-Text does not run with OPTION RAM

### ISSUE THREAD

**Issue by Bjoerg** [thwill1000/cmm2-welcome#25]
Screen turns black and nothing happens.
Not even able to break with ctrl-c

**Comment by thwill1000** [comment]
Hi Bjoerg,

Thanks for reporting this issue. Which version of the CMM2 firmware are you running? If it is earlier than 5.06.00 then this is to be expected.

Tom

**Comment by Bjoerg** [comment]
Hi Tom

running the newest 5.07.00.b11 Version.

Björg

**Comment by thwill1000** [comment]
Hi Bjoerg,

Thanks I will try and take a look this weekend.

Tom

**Comment by thwill1000** [comment]
FIXED

No changes to "The Welcome Tape" required, instead this was a transient firmware issue now fixed in 5.07.00.b12.
